name: Unit Tests 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: 
  pull_request:
  push:
  workflow_dispatch:

env:
  JIVE_PROCS: 1

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.6

      # Runs a single command using the runners shell
      - name: Unit Tests
        run: |
          julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.build();'
          julia --threads 2 --project --check-bounds=yes --depwarn=yes -e 'import Pkg; Pkg.test(; coverage=true)'
      
      - name: Codecov Upload
        run: |
          julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder());'
